---
window_manager_packages:
  - archlinux-wallpaper
  - blueman
  - cliphist
  - firefox
  - ghostty
  - gnome
  - grim
  - gsimplecal
  - hypridle
  - hyprland
  - hyprlock
  - hyprpaper
  - hyprpolkitagent
  - mako
  - network-manager-applet
  - nextcloud-client
  - noto-fonts
  - nwg-look
  - pavucontrol
  - polkit-gnome
  - qt5-wayland
  - rofi-wayland
  - shotwell
  - slurp
  - ttf-font-awesome
  - ttf-jetbrains-mono-nerd
  - vlc
  - vlc-plugin-ffmpeg
  - vlc-plugin-x265
  - waybar
  - wireplumber
  - xdg-desktop-portal-hyprland

window_manager_aur_packages:
  - bluetui
  - prezto-git
  - python-pywal16
  - yay


window_manager_services:
  - bluetooth
  - gdm
