---
window_manager_coprs:
  - pgdev/ghostty
  - solopasha/hyprland
  - che/nerd-fonts
  - tofik/nwg-shell
  - errornointernet/packages 

window_manager_packages:
  - blueman
  - cliphist
  - go
  - gtk3-devel
  - firefox
  - fontawesome-fonts
  - ghostty
  - gnome-software
  - google-noto-fonts-all
  - grim
  - hypridle
  - hyprland
  - hyprlock
  - hyprpaper
  - hyprpolkitagent
  - jetbrains-mono-fonts
  - mate-polkit
  - mako
  - nerd-fonts
  - network-manager-applet
  - nwg-look
  - pavucontrol
  - python3-pip
  - rofi-wayland
  - slurp
  - swaylock
  - vlc
  - wallust
  - waybar
  - wireplumber
  - xdg-desktop-portal-hyprland

window_manager_services:
  - gdm

window_manager_github_modules:
  - name: prezto
    repo: https://github.com/sorin-ionescu/prezto.git
    build_cmd: cp -r . ~/.zprezto
    dst_path: ~/.zprezto
    version: master
