---

# system shared
default_tz: Europe/London
smtp_host: smtp-relay.brevo.com
smtp_port: 587
smtp_security: starttls

# docker
docker_install_packages: true
docker_username: docker
docker_groups:
  - docker
docker_main_group: "{{ docker_groups[0] }}"
docker_socket: /var/run/docker.sock
docker_config_dir: /docker/config
docker_compose_dir: /docker/compose
docker_data_dir: /docker/data
docker_local_data_dir: /docker/localdata
docker_dirs:
  - "{{ docker_config_dir }}"
  - "{{ docker_compose_dir }}"
  - "{{ docker_data_dir }}"
  - "{{ docker_local_data_dir }}"

# secrets
smtp_username: "{{ vault_smtp_username }}"
smtp_password: "{{ vault_smtp_password }}"

pihole_web_passwd: "{{ vault_pihole_web_passwd }}"
