$ANSIBLE_VAULT;1.1;AES256
30393462396134316230336539363465303636373039333835656335326330386561353737303963
3765643035333566393739613434666136643936376437350a326533613533636239356366636433
38333031306264316137366666653834366138303163643332613232613962643330303736653564
3234336233343263350a623034343463326431636132303464343435393433666463616133353230
63336263653434353534393130346335663534376134316633376135613335633834653634623431
63376363346133633733616461366631323738666462326235643461626334386135326331323136
38363531353762636339353862373330373534333537343735626336663935306262383938663732
39363436363837623566613030316465643039396232373335393335346434306161643830623833
62373434306162323238623566626135623336623566656437396364616462396561353532626332
66346338323663346166323364396663613634373263366230663730616238653537373262323930
64356335343763663861343861336231383835313563316136343138613432343135663332656566
30613933636238346537376531643032653263386539616664303461623366613637363732646263
64633765373665316133613062316638663765346466663835613939653538623639363463386165
3335656639376366393733653363386232633263656432356662
